name: Ola, Mundo!

on: [push]

jobs:
  ola_mundo_jobs:
    runs_on: ubuntu-latest

    steps:
      -name: Checkout
       uses: actions/checkout@v2
      
      - name: Ola, Mundo!
        run: echo "Ol√°, Mundo!"
